### ISSUE TITLE
Support for private submodules with different secrets

### ISSUE THREAD

**Issue by max3903** [openshift/builder#159]
Hello,

I am trying to build a Dockerfile app from a Github private repo which includes various git-submodules and some are private.

My .gitmodules:
```
[submodule "sub-repo"]
	path = src/sub-repo
	url = ssh://git@github.com/myorg/sub-repo.git
	branch = master
```

I created 2 secrets:
```
kind: Secret
apiVersion: v1
metadata:
  name: github-main-repo
  namespace: myapp
  selfLink: /api/v1/namespaces/myapp/secrets/github-main-repo
  annotations:
    build.openshift.io/source-secret-match-uri-1: 'ssh://git@github.com/myorg/main-repo*'
type: kubernetes.io/ssh-auth
```
```
kind: Secret
apiVersion: v1
metadata:
  name: github-sub-repo
  namespace: myapp
  selfLink: /api/v1/namespaces/myapp/secrets/github-sub-repo
  annotations:
    build.openshift.io/source-secret-match-uri-1: 'ssh://git@github.com/myorg/sub-repo*'
type: kubernetes.io/ssh-auth
```
linked them to the builder and added them to my build config:
```
    sourceSecret:
      name: github-main-repo
    secrets:
      - secret:
          name: github-main-repo
      - secret:
          name: github-sub-repo
```

I can clone the main repo with the secret in `sourceSecret` but it then fails at cloning the submodule.

Is it a supported scenario? Is it something that could be supported? Otherwise what are my options?
